### ISSUE TITLE
Dynamic version scoring

### ISSUE THREAD

**Issue by Beanow** [friendica/dir#13]
The health scoring function `health_score_after_probe` at `include/site-health.php` attributes scores to older versions. However this is hard-coded.

The database keeps track of what versions sites are running though. As can be seen for example in http://dir.friendi.ca/versions which comes from the `site-health` table's `version` column.

Since this follows a semver-like pattern it could be parsed and used to determine which stable major and minor versions are released. Meaning the scoring algorithm won't have to be updated every time.

Alternatively we could ask the Friendica devs to move the version number from `boot.php` to a separate file, like `VERSION` so we can request this file directly from the github master branch.

**Comment by tobiasd** [comment]
> Alternatively we could ask the Friendica devs to move the version
> number from `boot.php` to a separate file, like `VERSION` so we can
> request this file directly from the github master branch.

The version of a node is available via the API, cant you use that?

    api/statusnet/config.[xml|json]

**Comment by Beanow** [comment]
@tobiasd this is what the current code does. It gets the version per server from `/friendica/json`. The difference is that you could use the **code's master branch** as your reference. Versus looking at **servers in the wild**.

**Comment by tobiasd** [comment]
Yes, ok

**Comment by tobiasd** [comment]
I've added a VERSION file with the 3.5.1 release.

**Comment by MrPetovan** [comment]
The next version is checking for the current stable and develop version stored on https://git.friendi.ca to compute health score.
