### ISSUE TITLE
Locations Sidebar Results

### ISSUE THREAD

**Issue by zeroadam** [friendica/dir#14]
When clicking USA in the locations side bar it shows only one result (currently - UX Watchdogs Public Group). However, when scrolling through the full list, there are many profiles with USA as their location.

**Comment by Hypolite** [comment]
Thanks for reporting this issue, I've noticed it for a while, but I'm not using the directory enough to look into it.

**Comment by Hypolite** [comment]
This has been fixed on https://dir.friendica.social by lowering MySQL's  `ft_min_word_len` config to `3` instead of `4`. There aren't any changes in the code.
