### ISSUE TITLE
Feature: build stats pruning functionality

### ISSUE THREAD

**Issue by Beanow** [friendica/dir#4]
After running the maintenance jobs for ~2 months now, I have generated 6.2MB of statistical data about site-probe speeds and profile scrape speeds. These are never displayed as detailed as they are stored in the database. So I think the timespan for these high detail statistics should be limited and older results should be averaged to save space.
- Add a threshold after which site-scrape will be a daily avg.
- Add a threshold after which site-scrape will be dropped.
- Add a threshold after which site-probe will be dropped.

**Comment by MrPetovan** [comment]
Detailed stats will be removed in the next version.
