### ISSUE TITLE
Feature list of recommended public servers broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/dir#40]
There is an issue with the 'features' on the list of public servers.
https://dir.friendica.social/servers

For libranet.de and some other nodes it is only showing:
HTTPS  √
+1 more

I don't know which page is fetched from the server to generate the feature list. Here is my nodeinfo for comparison:
https://libranet.de/nodeinfo/1.0

**Comment by annando** [comment]
I guess that this is due to the fact that we renamed the addons.

**Comment by MrPetovan** [comment]
Thanks for the hint, it makes sense.

**Comment by AlfredSK** [comment]
Looks much better now.
