### ISSUE TITLE
Missing isset() calls causing noisy logs

### ISSUE THREAD

**Issue by realkinetix** [friendica/dir#48]
As per this discussion https://social.isurf.ca/display/c443a55c965ad120636473c075262327 the apache logs show a bunch of noise:

[Fri Apr 13 14:20:35.564499 2018] [proxy_fcgi:error] [pid 13331:tid 139943668336384] [client 27.130.68.3:51872] AH01071: Got error 'PHP message: PHP Notice: Undefined index: pdesc in /home/socialdir/dir/include/submit.php on line 134\nPHP message: PHP Notice: Undefined index: locality in /home/socialdir/dir/include/submit.php on line 135\nPHP message: PHP Notice: Undefined index: region in /home/socialdir/dir/include/submit.php on line 136\nPHP message: PHP Notice: Undefined index: postal-code in /home/socialdir/dir/include/submit.php on line 137\nPHP message: PHP Notice: Undefined index: country-name in /home/socialdir/dir/include/submit.php on line 138\n'

**Comment by MrPetovan** [comment]
The current version of the directory is about to become deprecated, this is a won't fix.
