### ISSUE TITLE
Filter for explicit content nodes in Server list

### ISSUE THREAD

**Issue by tobiasd** [friendica/dir#58]
Now that node admins can mark their Friendica nodes for explicit content communities friendica/friendica#5373 it would be nice to have a display filter for the server list and account listing that filters out those nodes by default. There should be an option for the visitor of the directory to show those hidden entries from the listings.

Directory admin should also have a possibility to mark nodes for explicit content for the directory node.

**Comment by MrPetovan** [comment]
This data doesn't appear in the output of the `/friendica/json` endpoint that the directory uses.
